---

driver:
  name: default

platforms:
  - name: instance
    managed: false
    host: localhost
    image: none

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
